include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat missing returns as warnings instead of errors
    missing_return: warning
    # Treat unused imports as warnings
    unused_import: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Enable additional rules for better code quality
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    use_super_parameters: true