name: easyssh
description: A Flutter SSH file explorer application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.9.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true